development:
  archivist:
    - archivist1@example.com
  admin:
    - mjgiarlo@stanford.edu
    - jrudder@email.unc.edu
    - Steve.VanTuyl@oregonstate.edu
    - chris-diaz@northwestern.edu
    - shlakeuva@gmail.com
    - hparekh@nd.edu
test:
  archivist:
    - archivist1@example.com
    - archivist2@example.com
    - leland_himself@example.com
  admin_policy_object_editor:
    - archivist1@example.com
  donor:
    - donor1@example.com
    - leland_himself@example.com
  researcher:
    - archivist1@example.com
    - researcher1@example.com
  patron:
    - patron1@example.com
    - leland_himself@example.com

production:
  # Add roles for users here.
  admin:
    - mjgiarlo@stanford.edu
    - jrudder@email.unc.edu
    - steve.vantuyl@oregonstate.edu
    - chris-diaz@northwestern.edu
    - shlake@virginia.edu
    - hparekh@nd.edu
    - shanita@curationexperts.com
    - alicia@curationexperts.com

